#!/bin/bash

Icon1="🔊"
Icon2="🔇"

#Status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $3}' | tr -d '[]')
#Volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print $2*100"%" }')

#if [ "$Status" = "MUTED" ] ; then
#        echo " $Icon2 $Volume "
#else
#        echo " $Icon1 $Volume "
#fi


Status=$(pactl list sinks | awk 'NR==9{print $2}')
Volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1{print $5}')

if [ "$Status" = "yes" ] ; then
	echo " $Icon2 $Volume "
else
	echo " $Icon1 $Volume "
fi

